---
abstract: 'Store and retrieve Moose objects to a cache, via L<CHI>.'
author:
  - 'Steve Caldwell <scaldwell@gmail.com>'
build_requires:
  Test::Most: '0'
  Test::Pod: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, Dist::Milla version v1.0.9, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Storage-IO-CHI
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  CHI: '0'
  Moose: '0'
  MooseX::Role::Parameterized: '0'
  MooseX::Storage: '0'
  namespace::autoclean: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/stevecaldwell77/MooseX-Storage-IO-CHI/issues
  homepage: https://github.com/stevecaldwell77/MooseX-Storage-IO-CHI
  repository: https://github.com/stevecaldwell77/MooseX-Storage-IO-CHI.git
version: '0.03'
x_contributors:
  - 'Stephen Caldwell <steve@campusexplorer.com>'
